parser: "@typescript-eslint/parser"
env:
  es6: true
  node: false
  browser: true
globals:
  document: readonly
  window: readonly
  fetch: false
plugins:
  - "@typescript-eslint"
  - prettier
  - import
  - react
  - react-hooks
extends:
  - ../.eslintrc.yml
  - plugin:@typescript-eslint/recommended
  - prettier
  - prettier/@typescript-eslint
  - plugin:react/recommended
  - plugin:import/errors
  - plugin:import/typescript
settings:
  react:
    version: detect
rules:
  # React Hooks
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: error

  # Import
  ## Static Analysis
  import/default: error
  import/named: error
  import/no-absolute-path: error
  import/no-self-import: error
  import/no-unresolved: error

  ## Helpful Warnings
  import/no-deprecated: error
  import/no-extraneous-dependencies: "off"
  import/no-mutable-exports: error

  ## Module Systems
  import/no-commonjs: error
  import/no-amd: error
  import/unambiguous: error

  ## Style Guide
  import/exports-last: error
  import/extensions:
    - error
    - never
    - svg: always
      jpg: always
      jpeg: always
      png: always
      json: always
  import/first: error
  import/newline-after-import: error
  import/no-anonymous-default-export: error
  import/no-duplicates: error
  import/no-namespace: error
  import/order: error
  import/prefer-default-export: "off"

  # React
  react/button-has-type: error
  react/default-props-match-prop-types: error
  react/display-name: "off"
  react/no-access-state-in-setstate: error
  react/no-children-prop: error
  react/no-danger: error
  react/no-danger-with-children: error
  react/no-deprecated: error
  react/no-did-mount-set-state: error
  react/no-did-update-set-state: error
  react/no-direct-mutation-state: error
  react/no-find-dom-node: error
  react/no-is-mounted: error
  react/no-multi-comp: error
  react/no-redundant-should-component-update: error
  react/no-render-return-value: error
  react/no-typos: error
  react/no-string-refs: error
  react/no-this-in-sfc: error
  react/no-unescaped-entities: error
  react/no-unknown-property: error
  react/no-unused-prop-types: error
  react/no-unused-state: error
  react/no-will-update-set-state: error
  react/prefer-stateless-function: error
  react/prop-types: "off"
  react/react-in-jsx-scope: error
  react/require-default-props: error
  react/require-render-return: error
  react/sort-prop-types: error
  react/style-prop-object: error
  react/void-dom-elements-no-children: error
  react/jsx-boolean-value:
    - error
    - never
  react/jsx-closing-bracket-location:
    - error
    - tag-aligned
  react/jsx-curly-spacing:
    - error
    - when: never
  react/jsx-equals-spacing:
    - error
    - never
  react/jsx-first-prop-new-line:
    - error
    - multiline-multiprop
  # react/jsx-indent:
  #   - error
  #   - tab
  react/jsx-indent-props:
    - error
    - tab
  react/jsx-key: error
  react/jsx-no-bind:
    - error
    - allowArrowFunctions: true
  react/jsx-no-comment-textnodes: error
  react/jsx-no-duplicate-props:
    - error
    - ignoreCase: false
  # react/jsx-no-literals: error
  react/jsx-no-target-blank: error
  react/jsx-no-undef: error
  # react/jsx-one-expression-per-line: error
  # react/jsx-curly-brace-presence:
  #   - error
  #   - never
  react/jsx-pascal-case: error
  react/jsx-props-no-multi-spaces: error
  react/jsx-sort-default-props: error
  react/jsx-sort-props: error
  react/jsx-tag-spacing:
    - error
    - beforeSelfClosing: always
    # - beforeClosing: never
  react/jsx-uses-react: error
  react/jsx-uses-vars: error

  # TypeScript
  "@typescript-eslint/adjacent-overload-signatures": error
  "@typescript-eslint/array-type":
    - error
  "@typescript-eslint/explicit-function-return-type":
    - error
    - allowExpressions: true
  "@typescript-eslint/explicit-member-accessibility": error
  "@typescript-eslint/member-ordering":
    - error
    - default:
        - private-field
        - protected-field
        - public-field
        - private-constructor
        - protected-constructor
        - public-constructor
        - private-method
        - protected-method
        - public-method
  # "@typescript-eslint/no-angle-bracket-type-assertion": error
  "@typescript-eslint/no-array-constructor": error
  "@typescript-eslint/no-empty-interface": "off"
  "@typescript-eslint/no-explicit-any": error
  "@typescript-eslint/no-extraneous-class": error
  "@typescript-eslint/no-for-in-array": error
  "@typescript-eslint/no-inferrable-types":
    - error
    - ignoreParameters: true
      ignoreProperties: true
  "@typescript-eslint/no-misused-new": error
  "@typescript-eslint/no-namespace": error
  "@typescript-eslint/no-non-null-assertion": "off"
  # "@typescript-eslint/no-object-literal-type-assertion": error
  "@typescript-eslint/no-parameter-properties": error
  "@typescript-eslint/no-require-imports": error
  "@typescript-eslint/no-this-alias": error
  # "@typescript-eslint/no-triple-slash-reference": error
  # "@typescript-eslint/no-unnecessary-qualifier": error
  # "@typescript-eslint/no-unnecessary-type-assertion": error
  "@typescript-eslint/no-unused-vars": 0
  "@typescript-eslint/no-use-before-define": error
  "@typescript-eslint/no-useless-constructor": error
  "@typescript-eslint/no-var-requires": error
  "@typescript-eslint/prefer-function-type": error
  "@typescript-eslint/prefer-interface": "off"
  "@typescript-eslint/prefer-namespace-keyword": error
  # "@typescript-eslint/promise-function-async": error
  "@typescript-eslint/type-annotation-spacing":
    - error
    - before: false
      after: true
      overrides:
        arrow:
          before: true
          after: true
