globals:
  afterAll: true
  beforeAll: true
  describe: true
  expect: true
  it: true
rules:
  # Possible Errors
  for-direction: error
  getter-return: error
  no-async-promise-executor: error
  no-await-in-loop: error
  no-compare-neg-zero: error
  no-cond-assign: error
  no-console: error
  no-constant-condition:
    - error
    - checkLoops: false
  no-control-regex: error
  no-debugger: error
  no-dupe-args: error
  no-dupe-keys: error
  no-duplicate-case: error
  no-empty: error
  no-empty-character-class: error
  no-ex-assign: error
  no-extra-boolean-cast: error
  no-extra-parens: "off"
  no-extra-semi: error
  no-func-assign: error
  no-inner-declarations: error
  no-invalid-regexp: error
  no-irregular-whitespace: error
  no-misleading-character-class: error
  no-obj-calls: error
  no-regex-spaces: error
  no-sparse-arrays: error
  no-template-curly-in-string: error
  no-unexpected-multiline: error
  no-unreachable: error
  no-unsafe-finally: error
  no-unsafe-negation: error
  require-atomic-updates: error
  use-isnan: error
  valid-typeof: error

  # Best Practices
  block-scoped-var: error
  class-methods-use-this: error
  curly:
    - error
    - all
  default-case: error
  dot-location:
    - error
    - property
  dot-notation: error
  eqeqeq: error
  no-alert: error
  no-caller: error
  no-case-declarations: error
  no-div-regex: error
  no-else-return: error
  no-empty-function: "off"
  no-empty-pattern: error
  no-eq-null: error
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: error
  no-fallthrough: error
  no-floating-decimal: error
  no-global-assign: error
  no-implicit-coercion: error
  no-implied-eval: error
  no-invalid-this: error
  no-iterator: error
  no-labels: error
  no-lone-blocks: error
  no-loop-func: error
  # no-magic-numbers: error
  no-multi-spaces: error
  no-multi-str: error
  no-new: error
  no-new-func: error
  no-new-wrappers: error
  no-octal: "off"
  no-octal-escape: error
  no-param-reassign: error
  no-proto: error
  no-redeclare: error
  no-return-assign: error
  no-return-await: error
  no-script-url: error
  no-self-assign: error
  no-self-compare: error
  no-sequences: error
  no-throw-literal: error
  no-unmodified-loop-condition: error
  no-unused-expressions: error
  no-unused-labels: error
  no-useless-call: error
  no-useless-catch: error
  no-useless-concat: error
  no-useless-escape: error
  no-useless-return: error
  no-void: error
  no-with: error
  prefer-promise-reject-errors: error
  radix: error
  require-await: "off"
  require-unicode-regexp: error
  wrap-iife: error
  yoda: error

  # Strict Mode
  strict: error

  # Variables
  no-delete-var: error
  no-label-var: error
  no-shadow: error
  no-shadow-restricted-names: error
  no-undef: error
  no-undef-init: error
  no-undefined: "off"
  no-unused-vars: "off"
  no-use-before-define: error

  # Node.js and CommonJS
  global-require: error
  no-buffer-constructor: error
  no-new-require: error
  no-path-concat: error
  # no-sync: error
  # Stylistic Issues
