image: node:10

stages:
  - setup
  - build

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - server/node_modules/
    # - coronavirus-client/node_modules/

before_script:
  - yarn --cwd ./server/
  # - yarn --cwd ./coronavirus-client/

setup_server:
  stage: setup
  script:
    - yarn --cwd ./server/ lint

build_server:
  stage: build
  script:
    - yarn --cwd ./server/ build
# build_client:
#   stage: build
#   script:
#     - yarn --cwd ./coronavirus-client/ build
