image: node:16-alpine

stages:
  - setup
  - build
  - release

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ./server/node_modules/
    - ./client/node_modules/

setup_server:
  stage: setup
  script:
    - yarn --cwd ./server
    - yarn --cwd ./server/ lint

build_server:
  stage: build
  script:
    - yarn --cwd ./server
    - SKIP_PREFLIGHT_CHECK=true yarn --cwd ./server/ build

setup_client:
  stage: setup
  script:
    - yarn --cwd ./server
    - yarn --cwd ./client/ lint

build_client:
  stage: build
  script:
    - yarn --cwd ./server
    - yarn --cwd ./client/ build

push_image:
  stage: release
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
    - node:16-alpine
    - mariadb:10
  variables:
    CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CONTAINER_RELEASE_IMAGE .
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master
    - deploy
