image: node:10

stages:
  - setup
  - build
  - release

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ./server/node_modules/
    - ./client/node_modules/

variables:
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

before_script:
  - yarn --cwd ./server/
  - yarn --cwd ./client/
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

setup_server:
  stage: setup
  script:
    - yarn
    - yarn --cwd ./server/ lint

build_server:
  stage: build
  script:
    - yarn
    - SKIP_PREFLIGHT_CHECK=true yarn --cwd ./server/ build

setup_client:
  stage: setup
  script:
    - yarn --cwd ./client/ lint

build_client:
  stage: build
  script:
    - yarn --cwd ./client/ build

push_image:
  stage: release
  script:
    - docker build -t $CONTAINER_RELEASE_IMAGE .
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master
    - deploy
