image: node:10

stages:
  - setup
  - build

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ./server/node_modules/
    - ./client/node_modules/

before_script:
  - yarn --cwd ./server/
  - yarn --cwd ./client/

setup_server:
  stage: setup
  script:
    - yarn
    - yarn --cwd ./server/ lint

build_server:
  stage: build
  script:
    - yarn
    - SKIP_PREFLIGHT_CHECK=true yarn --cwd ./server/ build

setup_client:
  stage: setup
  script:
    - yarn --cwd ./client/ lint

build_client:
  stage: build
  script:
    - yarn --cwd ./client/ build
