version: "3.6"

services:
  mariadb:
    image: mariadb:10
    container_name: myma-store-mariadb
    hostname: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yasskin
      MYSQL_DATABASE: MYMAStore
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    container_name: myma-store-phpmyadmin
    hostname: phpmyadmin
    restart: always
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
    ports:
      - 3307:80
  store:
    container_name: store
    hostname: store
    user: myma
    links:
      - mariadb
    depends_on:
      - mariadb
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        server_domain: ${REACT_APP_SERVER_DOMAIN:-"http://localhost:8080"}
        environment: "development"
    ports:
      - 8080:8080
    volumes:
      - ${MYMA_PRODUCTS_HOST_PATH:-./products}:/myma-store/products:Z
