version: "3.6"

services:
  mariadb:
    image: mariadb:10
    container_name: myma-store-mariadb
    hostname: mariadb
    restart: "no"
    env_file: ${MARIADB_PROD_ENV:-mariadb.prod.env}
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    container_name: myma-store-phpmyadmin
    hostname: phpmyadmin
    restart: "no"
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
    ports:
      - 3307:80

  myma-store:
    container_name: myma-store
    hostname: myma-store
    user: myma
    depends_on:
      - mariadb
    restart: "no"
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        environment: "production"
    ports:
      - 8080:8080
    volumes:
      - ${MYMA_PRODUCTS_PATH:-products}:/myma-store/products:ro
