version: "3.6"

services:
  mariadb:
    image: mariadb:10
    container_name: myma-store-mariadb
    hostname: mariadb
    restart: "no"
    environment:
      MYSQL_DATABASE: ${MYMA_STORE_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYMA_STORE_DATABASE_PASSWORD}
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    container_name: myma-store-phpmyadmin
    hostname: phpmyadmin
    restart: "no"
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
    ports:
      - 3307:80
  store:
    container_name: store
    hostname: store
    user: myma
    depends_on:
      - mariadb
    restart: "no"
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        server_domain: ${REACT_APP_SERVER_DOMAIN:-"https://mymathapps.com"}
        environment: "production"
    ports:
      - 8080:8080
    volumes:
      - ${MYMA_PRODUCTS_HOST_PATH:-./products}:/myma-store/products:Z
