parser: "@typescript-eslint/parser"
env:
  es6: true
  node: true
plugins:
  - "@typescript-eslint"
  - import
extends:
  - ../.eslintrc.yml
  - plugin:@typescript-eslint/recommended
  - prettier
  - prettier/@typescript-eslint
  - plugin:import/errors
  - plugin:import/typescript
rules:
  # Import
  ## Static Analysis
  import/default: error
  import/named: error
  import/no-absolute-path: error
  import/no-self-import: error
  import/no-unresolved: error

  ## Helpful Warnings
  import/no-deprecated: error
  import/no-extraneous-dependencies: "off"
  import/no-mutable-exports: error

  ## Module Systems
  import/no-commonjs: error
  import/no-amd: error
  import/unambiguous: error

  ## Style Guide
  import/exports-last: error
  import/extensions:
    - error
    - never
    - svg: always
      jpg: always
      jpeg: always
      png: always
      json: always
  import/first: error
  import/newline-after-import: error
  import/no-anonymous-default-export: error
  import/no-duplicates: error
  # import/no-namespace: error
  import/order: error
  import/prefer-default-export: error

  # TypeScript
  "@typescript-eslint/adjacent-overload-signatures": error
  "@typescript-eslint/array-type":
    - error
    - default: array-simple
      readonly: array-simple
  "@typescript-eslint/ban-ts-ignore": error
  "@typescript-eslint/camelcase":
    - error
    - properties: always
  "@typescript-eslint/class-name-casing": error
  "@typescript-eslint/explicit-function-return-type":
    - error
    - allowExpressions: true
  "@typescript-eslint/explicit-member-accessibility": error
  "@typescript-eslint/interface-name-prefix":
    - error
    - never
  "@typescript-eslint/member-ordering":
    - error
    - default:
        - private-field
        - protected-field
        - public-field
        - private-constructor
        - protected-constructor
        - public-constructor
        - private-method
        - protected-method
        - public-method
  # "@typescript-eslint/no-angle-bracket-type-assertion": error
  "@typescript-eslint/no-array-constructor": error
  "@typescript-eslint/no-empty-interface": "off"
  "@typescript-eslint/no-explicit-any": error
  "@typescript-eslint/no-extraneous-class": error
  "@typescript-eslint/no-for-in-array": error
  "@typescript-eslint/no-inferrable-types":
    - error
    - ignoreParameters: true
      ignoreProperties: true
  "@typescript-eslint/no-misused-new": error
  "@typescript-eslint/no-namespace": error
  "@typescript-eslint/no-non-null-assertion": "off"
  "@typescript-eslint/no-object-literal-type-assertion": "off"
  "@typescript-eslint/no-parameter-properties": "off"
  "@typescript-eslint/no-require-imports": error
  "@typescript-eslint/no-this-alias": error
  # "@typescript-eslint/no-unnecessary-qualifier": error
  # "@typescript-eslint/no-unnecessary-type-assertion": error
  "@typescript-eslint/no-unused-vars": "off"
  "@typescript-eslint/no-use-before-define": error
  "@typescript-eslint/no-useless-constructor": error
  "@typescript-eslint/no-var-requires": error
  "@typescript-eslint/prefer-function-type": error
  "@typescript-eslint/prefer-interface": "off"
  "@typescript-eslint/prefer-namespace-keyword": error
  # "@typescript-eslint/promise-function-async": error
  "@typescript-eslint/type-annotation-spacing":
    - error
    - before: false
      after: true
      overrides:
        arrow:
          before: true
          after: true
